language: java
sudo: false
script: mvn clean verify
before_script:
- chmod +x update-gh-pages.sh
after_success:
- mvn -DwithHistory=true org.pitest:pitest-maven:mutationCoverage
- .utility/update-gh-pages.sh
env:
  global:
    secure: dKsMQKxGi96SfbTUgFtnJgQMLfEWr6H6GhqkUjXZ+RitTj8zO8RFVb8O85Ovb03Sv+fSr6jq1Rz6s5nmMiXITSp2KuH95Cw5qf89kt8k64KsVMhipOnUosCj/IpljAS46qGFrVSH6uvAx8PiFzKRvg/FlpLgwLUCBbFhT/NBLeEwCYptjrCKJReaiK1T2bvAfk2u+Qob7uQg9nUPBj4pbreXji3K8YyqtTwcPsdaOzSDexbz47livG/q7sh7nFysE9lRIVVr++WuA/OMIGLopckyK+s2uqyLBO473cb9CHWcod13/ORYp2VevcP++D91Sg5KGz7uiyxVqTSHv5vHMUVg/EkBTpoQ3ecdeiSswUWqrkySPIIsaw5IT6FrpzrTuk9mY4jn2JcwSy4jkAlXt+qfwc4fYcWrPB0ORsmRermy9hXAMA6agZvDYqa7Qt4MrJa6J9oTi/TyD1o623TSOboKrKvgjn1WnbVzmr2dJCIFw1b3bWR85h7FT1SnqiePC8xD1GB6L2Rvk9oiPqfjRF9NDIVgM25RK9zXARQEXCAmhhjfT07rmYzidtOZY3/aqsy+ibbgoXdXTOyZ0/FQzQxADPbdbCT8YElYTo2b/P5Q+AFya8K01WW7I2d0HnTQlg6KHsxPh4CDd4aGhKgXc6kBVSUq1x46551PVPcaivw=
